modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "separatedleaves"
version = "${version}"
displayName = "Separated Leaves"
authors = "LarsMans"
description = '''
This mod makes leaves only connect to their own log type
'''
logoFile = "icon.png"

[[dependencies.separatedleaves]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.separatedleaves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.separatedleaves]]
modId = "architectury"
mandatory = true
versionRange = "[7.1.86,)"
ordering = "AFTER"
side = "BOTH"